In [1]:
import torch
import numpy as np

In [2]:
x = torch.tensor([[1.0, -1.0], [1.0, -1.0]])

print(x)

tensor([[ 1., -1.],
        [ 1., -1.]])


In [3]:
mask = torch.zeros(x.shape, dtype=torch.float64)
print(mask)

tensor([[0., 0.],
        [0., 0.]], dtype=torch.float64)


In [4]:
# Função corrigida
def _rank_explanation(explanation):
    return np.argsort(explanation)[::-1].copy()

# Dados de teste simples
data = torch.tensor([
    [1.5, 2.3, 0.8, 1.2, 3.1],
    [2.1, 1.7, 1.5, 0.9, 2.8]
], dtype=torch.float64)

explanation = np.array([0.1, 0.8, 0.3, 0.05, 0.9])
n_features = 3

# Teste
mask = torch.zeros(data.shape, dtype=torch.float64)
important_features = _rank_explanation(explanation)[:n_features]
mask[:, important_features] = data[:, important_features]

print("Data:", data)
print("Explanation:", explanation)
print("Important features:", important_features)
print("Mask:", mask)

Data: tensor([[1.5000, 2.3000, 0.8000, 1.2000, 3.1000],
        [2.1000, 1.7000, 1.5000, 0.9000, 2.8000]], dtype=torch.float64)
Explanation: [0.1  0.8  0.3  0.05 0.9 ]
Important features: [4 1 2]
Mask: tensor([[0.0000, 2.3000, 0.8000, 0.0000, 3.1000],
        [0.0000, 1.7000, 1.5000, 0.0000, 2.8000]], dtype=torch.float64)


In [5]:
for data in mask:
    print(data)

tensor([0.0000, 2.3000, 0.8000, 0.0000, 3.1000], dtype=torch.float64)
tensor([0.0000, 1.7000, 1.5000, 0.0000, 2.8000], dtype=torch.float64)
